name: Update Version File

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version from Release Tag
        run: echo "${{ github.event.release.tag_name }}" > version.txt

      - name: Commit and Push Version File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Update version.txt to ${{ github.event.release.tag_name }}"
          git push
